<?php

namespace Proxies\__CG__\ControlacFIEC\TodoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuario extends \ControlacFIEC\TodoBundle\Entity\Usuario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Usuario' . "\0" . 'usuarioName', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Usuario' . "\0" . 'usuarioApellido', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Usuario' . "\0" . 'usuarioMail', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Usuario' . "\0" . 'usuarioUser', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Usuario' . "\0" . 'usuarioPasword', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Usuario' . "\0" . 'userId'];
        }

        return ['__isInitialized__', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Usuario' . "\0" . 'usuarioName', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Usuario' . "\0" . 'usuarioApellido', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Usuario' . "\0" . 'usuarioMail', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Usuario' . "\0" . 'usuarioUser', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Usuario' . "\0" . 'usuarioPasword', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Usuario' . "\0" . 'userId'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getUsuarioMail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioMail', []);

        return parent::getUsuarioMail();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioMail(string $usuarioMail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioMail', [$usuarioMail]);

        return parent::setUsuarioMail($usuarioMail);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioName', []);

        return parent::getUsuarioName();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioName(string $usuarioName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioName', [$usuarioName]);

        return parent::setUsuarioName($usuarioName);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioApellido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioApellido', []);

        return parent::getUsuarioApellido();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioApellido(string $usuarioApellido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioApellido', [$usuarioApellido]);

        return parent::setUsuarioApellido($usuarioApellido);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioUser', []);

        return parent::getUsuarioUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioUser(string $usuarioUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioUser', [$usuarioUser]);

        return parent::setUsuarioUser($usuarioUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioPasword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioPasword', []);

        return parent::getUsuarioPasword();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioPasword(string $usuarioPasword)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioPasword', [$usuarioPasword]);

        return parent::setUsuarioPasword($usuarioPasword);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getUserId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', []);

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserId($userId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserId', [$userId]);

        return parent::setUserId($userId);
    }

}
