<?php

namespace Proxies\__CG__\ControlacFIEC\TodoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Materias extends \ControlacFIEC\TodoBundle\Entity\Materias implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Materias' . "\0" . 'materiasName', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Materias' . "\0" . 'materiasCodigo', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Materias' . "\0" . 'materiasActivo', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Materias' . "\0" . 'materiasId'];
        }

        return ['__isInitialized__', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Materias' . "\0" . 'materiasName', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Materias' . "\0" . 'materiasCodigo', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Materias' . "\0" . 'materiasActivo', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Materias' . "\0" . 'materiasId'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Materias $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getMateriasName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMateriasName', []);

        return parent::getMateriasName();
    }

    /**
     * {@inheritDoc}
     */
    public function setMateriasName(string $materiasName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMateriasName', [$materiasName]);

        return parent::setMateriasName($materiasName);
    }

    /**
     * {@inheritDoc}
     */
    public function getMateriasCodigo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMateriasCodigo', []);

        return parent::getMateriasCodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setMateriasCodigo(string $materiasCodigo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMateriasCodigo', [$materiasCodigo]);

        return parent::setMateriasCodigo($materiasCodigo);
    }

    /**
     * {@inheritDoc}
     */
    public function getMateriasActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMateriasActivo', []);

        return parent::getMateriasActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setMateriasActivo($materiasActivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMateriasActivo', [$materiasActivo]);

        return parent::setMateriasActivo($materiasActivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getMateriasId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getMateriasId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMateriasId', []);

        return parent::getMateriasId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMateriasId($materiasId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMateriasId', [$materiasId]);

        return parent::setMateriasId($materiasId);
    }

}
