<?php

namespace Proxies\__CG__\ControlacFIEC\TodoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class HorarioClase extends \ControlacFIEC\TodoBundle\Entity\HorarioClase implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\HorarioClase' . "\0" . 'horarioClaseDiaNum', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\HorarioClase' . "\0" . 'horarioClaseName', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\HorarioClase' . "\0" . 'horarioClaseTimeInicio', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\HorarioClase' . "\0" . 'horarioClaseTimeFin', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\HorarioClase' . "\0" . 'horarioClaseId', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\HorarioClase' . "\0" . 'horarioClaseCurso'];
        }

        return ['__isInitialized__', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\HorarioClase' . "\0" . 'horarioClaseDiaNum', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\HorarioClase' . "\0" . 'horarioClaseName', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\HorarioClase' . "\0" . 'horarioClaseTimeInicio', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\HorarioClase' . "\0" . 'horarioClaseTimeFin', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\HorarioClase' . "\0" . 'horarioClaseId', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\HorarioClase' . "\0" . 'horarioClaseCurso'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (HorarioClase $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getHorarioClaseDiaNum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorarioClaseDiaNum', []);

        return parent::getHorarioClaseDiaNum();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorarioClaseDiaNum($horarioClaseDiaNum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorarioClaseDiaNum', [$horarioClaseDiaNum]);

        return parent::setHorarioClaseDiaNum($horarioClaseDiaNum);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorarioClaseName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorarioClaseName', []);

        return parent::getHorarioClaseName();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorarioClaseName(string $horarioClaseName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorarioClaseName', [$horarioClaseName]);

        return parent::setHorarioClaseName($horarioClaseName);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorarioClaseId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getHorarioClaseId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorarioClaseId', []);

        return parent::getHorarioClaseId();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorarioClaseId($horarioClaseId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorarioClaseId', [$horarioClaseId]);

        return parent::setHorarioClaseId($horarioClaseId);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorarioClaseCurso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorarioClaseCurso', []);

        return parent::getHorarioClaseCurso();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorarioClaseCurso(\ControlacFIEC\TodoBundle\Entity\Curso $horarioClaseCurso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorarioClaseCurso', [$horarioClaseCurso]);

        return parent::setHorarioClaseCurso($horarioClaseCurso);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorarioClaseTimeInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorarioClaseTimeInicio', []);

        return parent::getHorarioClaseTimeInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorarioClaseTimeInicio(\DateTime $horarioClaseTimeInicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorarioClaseTimeInicio', [$horarioClaseTimeInicio]);

        return parent::setHorarioClaseTimeInicio($horarioClaseTimeInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorarioClaseTimeFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorarioClaseTimeFin', []);

        return parent::getHorarioClaseTimeFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorarioClaseTimeFin(\DateTime $horarioClaseTimeFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorarioClaseTimeFin', [$horarioClaseTimeFin]);

        return parent::setHorarioClaseTimeFin($horarioClaseTimeFin);
    }

}
