<?php

namespace Proxies\__CG__\ControlacFIEC\TodoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Curso extends \ControlacFIEC\TodoBundle\Entity\Curso implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Curso' . "\0" . 'cursoName', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Curso' . "\0" . 'cursoCodigo', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Curso' . "\0" . 'cursoParalelo', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Curso' . "\0" . 'cursoId', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Curso' . "\0" . 'cursoMateria', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Curso' . "\0" . 'cursoDocente', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Curso' . "\0" . 'cursoSemestre', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Curso' . "\0" . 'cursoCargarClase'];
        }

        return ['__isInitialized__', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Curso' . "\0" . 'cursoName', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Curso' . "\0" . 'cursoCodigo', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Curso' . "\0" . 'cursoParalelo', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Curso' . "\0" . 'cursoId', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Curso' . "\0" . 'cursoMateria', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Curso' . "\0" . 'cursoDocente', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Curso' . "\0" . 'cursoSemestre', '' . "\0" . 'ControlacFIEC\\TodoBundle\\Entity\\Curso' . "\0" . 'cursoCargarClase'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Curso $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCursoName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCursoName', []);

        return parent::getCursoName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCursoName(string $cursoName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCursoName', [$cursoName]);

        return parent::setCursoName($cursoName);
    }

    /**
     * {@inheritDoc}
     */
    public function getCursoCodigo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCursoCodigo', []);

        return parent::getCursoCodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCursoCodigo(string $cursoCodigo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCursoCodigo', [$cursoCodigo]);

        return parent::setCursoCodigo($cursoCodigo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCursoParalelo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCursoParalelo', []);

        return parent::getCursoParalelo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCursoParalelo(string $cursoParalelo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCursoParalelo', [$cursoParalelo]);

        return parent::setCursoParalelo($cursoParalelo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCursoId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCursoId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCursoId', []);

        return parent::getCursoId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCursoId($cursoId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCursoId', [$cursoId]);

        return parent::setCursoId($cursoId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCursoMateria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCursoMateria', []);

        return parent::getCursoMateria();
    }

    /**
     * {@inheritDoc}
     */
    public function setCursoMateria(\ControlacFIEC\TodoBundle\Entity\Materias $cursoMateria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCursoMateria', [$cursoMateria]);

        return parent::setCursoMateria($cursoMateria);
    }

    /**
     * {@inheritDoc}
     */
    public function getCursoDocente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCursoDocente', []);

        return parent::getCursoDocente();
    }

    /**
     * {@inheritDoc}
     */
    public function setCursoDocente(\ControlacFIEC\TodoBundle\Entity\Usuario $cursoDocente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCursoDocente', [$cursoDocente]);

        return parent::setCursoDocente($cursoDocente);
    }

    /**
     * {@inheritDoc}
     */
    public function getCursoSemestre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCursoSemestre', []);

        return parent::getCursoSemestre();
    }

    /**
     * {@inheritDoc}
     */
    public function setCursoSemestre(\ControlacFIEC\TodoBundle\Entity\Semestre $cursoSemestre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCursoSemestre', [$cursoSemestre]);

        return parent::setCursoSemestre($cursoSemestre);
    }

    /**
     * {@inheritDoc}
     */
    public function getCursoCargarClase()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCursoCargarClase', []);

        return parent::getCursoCargarClase();
    }

    /**
     * {@inheritDoc}
     */
    public function setCursoCargarClase($cursoCargarClase)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCursoCargarClase', [$cursoCargarClase]);

        return parent::setCursoCargarClase($cursoCargarClase);
    }

}
