security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_firewall:
            pattern:    ^/backend/login$
            anonymous:  ~

        login_check_firewall:
            pattern:    ^/backend/login_check$
            anonymous:  ~

        secured_area:
             pattern:  ^/backend
             anonymous: false
             form_login:
                csrf_provider: form.csrf_provider
                intention: authenticate
                use_forward: true
                check_path: login_check
                login_path: login

        l3_firewall:
            pattern: ^/backend
            security: true
            cas: true # Activation du CAS

    providers:
         in_memory:
             memory: ~

    encoders:
          Symfony\Component\Security\Core\User\User: plaintext


    access_control:
        - { path: ^/backend/curso/*, allow_if: "has_role('ROLE_DOCENTE') or has_role('ROLE_COORDINADOR')" }
        - { path: ^/backend/admin/*, allow_if: "has_role('ROLE_ADMIN')"  }
